[package]
name = "astarbis"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.8"
rand = "0.8.4"
lazy_static = "1.4.0"
priority-queue = "2.0.2"

[profile.release]
opt-level = 3
lto = true
